name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag knex666/shortipy:latest-dev
    - name: login and push
      run: docker login -u knex666 -p ${{secrets.DOCKER_HUB_TOKEN}}
           docker push knex666/shortipy:latest-dev
